spring:
  datasource:
    url: jdbc:mysql://localhost/cloud_tmall?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    suffix: .html
tmall: 
  datasource: 
    url: jdbc:mysql://localhost/cloud_tmall?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
key:
  login-public-key-path: 'classpath:keys/login_public.key'
  login-private-key-path: 'classpath:keys/login_private.key'
  portal-public-key-path: 'classpath:keys/portal_public.key'
server:
  port: 8000

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations:
#  - classpath:mapper/*.xml
