#spring: 
#  freemarker:
#    suffix: .html
spring: 
  application:
    name: ssyo-system
tmall: 
  config: 
    url: jdbc:mysql://localhost/tmall_micro?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    amqp-enabled: true
    email-account: 18757883747@163.com
    email-pwd: lvcong1215
    email-host: smtp.163.com
    mysql-extention: user:1:2
key:
  login-public-key-path: 'classpath:keys/login_public.key'
  login-private-key-path: 'classpath:keys/login_private.key'
  portal-public-key-path: 'classpath:keys/portal_public.key'
server:
  port: 9000
  
  
  
  
  
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost
    
    
    
debug: true


