##spring:
 ## datasource:
 ##   username: root
##    password: 123456
##    url: jdbc:mysql://localhost/tmall_record?characterEncoding=utf-8&useSSL=false
##   driver-class-name: com.mysql.jdbc.Driver
    
    
    
    
    
tmall: 
  config: 
    mq: 
      amqp-addrss: localhost
      amqp-port: 5672
      amqp-username: guest
      amqp-password: guest
      amqp-enabled: true
    db: 
      username: root
      password: 123456
      url: jdbc:mysql://localhost/tmall_record?characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver