
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ItsFunny/tmall-config.git
          username: 18757883747@163.com
          password: lvcong0402@
