spring:
  application:
    name: AUTH
tmall:
  config:
    url: jdbc:mysql://localhost/tmall_micro?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    amqp-enabled: false
    email-account: 18757883747@163.com
    email-pwd:
    email-host: smtp.163.com
    mysql-extention: user:2
    amqp-host: localhost
    amqp-username: guest
    amqp-password: guest
  key:
    auth-public-key-path: classpath:keys/auth_public.key
    auth-private-key-path: classpath:keys/auth_private.key
    sso-public-key-path: classpath:keys/sso_public.key
    sso-private-key-path: classpath:keys/sso_private.key
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
debug: true
