spring:
  application:
    name: admin
tmall: 
  config: 
    application-name: ${spring.application.name}
    url: jdbc:mysql://localhost/tmall_micro?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    amqpEnabled: false
    email-account: 18757883747@163.com
    email-pwd: lvcong1215
    email-host: smtp.163.com
    mysql-extention: user:2
    amqp-host: localhost
    amqp-username: guest
    amqp-password: guest
    admin: 
      auth-detail-url: 
      db-url: jdbc:mysql://localhost/tmall_micro?characterEncoding=utf-8&useSSL=false
      db-username: root
      db-password: 123456
      db-driver-class-name: com.mysql.jdbc.Drivler
      amqpEnabled: false
  key:
    auth-public-key-path: classpath:keys/auth_public.key
    auth-private-key-path: classpath:keys/auth_private.key
    sso-public-key-path: classpath:keys/sso_public.key
    sso-private-key-path: classpath:keys/sso_private.key
server:
  port: 9002
    
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost

feign: 
  hystrix: 
    enabled: true
    
    
#hystrix:
#  command: 
#    default: 
#      execution:
#        timeout:
#          enabled: false   
    
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
debug: true