#spring: 
#  freemarker:
#    suffix: .html
spring: 
  application:
    name: management-system
  profiles:
    active:
    - dev



debug: true


logging.level:
          org:
            datacontract: ERROR
            apache:
              commons.httpclient: ERROR
              axis2: ERROR
          com:
            leverate: ERROR
            microsoft: ERROR
            tradingcrm: ERROR